### ISSUE TITLE
Smart Forest Project Review

### ISSUE THREAD

**Issue by RolandoTrejo** [CIEE-Living-Data-Project/Parfitt_LDP_prod_repro_SmartForests#2]
All the components to initialize a reproducible project are on the OSF page: 

1. I suggest creating a data component in OSF linking the GitHub folder's current data folder. It will be easy to associate the same components in OSF and GitHub. 
3. I would create a new folder in GitHub called images to save the main manuscript figures.
4. It seems that the Pre-registration component is in drafts. 
5. I would rename the repository name like [Parfitt_SmartForests]. In the README file, I would describe what LDP means, the course name, and the main affiliation of this curse (LDP: Living Data Project).

**Comment by ian-parfitt** [comment]
Thanks Rolando, I'll consider these ideas.  I like numbers 1 and 2, currently the pre-reg is only the wiki page so I'll get on that.  I don't think I'll change the name of the repo at the moment.
